import type { Fonte } from "./tipos";

const PLANALTO = "Presidência da República — texto compilado (planalto.gov.br)";
const CONFERIDO = "2026-09-02";
const CONFERIDO_AMPLIACAO = "2026-09-04";

/**
 * Seed de legislação transcrita da fonte oficial.
 *
 * Este arquivo é deliberadamente pequeno e curado à mão. Ele NÃO é o corpus
 * final da plataforma — é o núcleo verificado que permite operar o V1 sem que
 * a IA precise inventar dispositivo nenhum. A ingestão automatizada do acervo
 * completo (LexML / Planalto) está descrita em docs/FUNDAMENTACAO.md e é o
 * primeiro item de infraestrutura do V2.
 *
 * Regra para incluir um dispositivo aqui: texto literal conferido contra a URL
 * oficial, com a data da conferência preenchida em `verificadoEm`.
 */
export const LEGISLACAO: Fonte[] = [
  // ---------------------------------------------------------------------
  // Constituição Federal de 1988
  // ---------------------------------------------------------------------
  {
    id: "cf88-art1",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 1º",
    ementa: "Fundamentos da República e titularidade do poder",
    texto:
      "A República Federativa do Brasil, formada pela união indissolúvel dos Estados e Municípios e do Distrito Federal, constitui-se em Estado Democrático de Direito e tem como fundamentos: I - a soberania; II - a cidadania; III - a dignidade da pessoa humana; IV - os valores sociais do trabalho e da livre iniciativa; V - o pluralismo político. Parágrafo único. Todo o poder emana do povo, que o exerce por meio de representantes eleitos ou diretamente, nos termos desta Constituição.",
    areas: ["direito constitucional", "teoria geral do estado", "ciência política"],
    sinonimos: ["soberania popular", "estado democrático de direito", "dignidade da pessoa humana"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art2",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 2º",
    ementa: "Separação dos Poderes",
    texto:
      "São Poderes da União, independentes e harmônicos entre si, o Legislativo, o Executivo e o Judiciário.",
    areas: ["direito constitucional", "teoria geral do estado", "ciência política"],
    sinonimos: ["tripartição de poderes", "freios e contrapesos", "montesquieu"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art3",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 3º",
    ementa: "Objetivos fundamentais da República",
    texto:
      "Constituem objetivos fundamentais da República Federativa do Brasil: I - construir uma sociedade livre, justa e solidária; II - garantir o desenvolvimento nacional; III - erradicar a pobreza e a marginalização e reduzir as desigualdades sociais e regionais; IV - promover o bem de todos, sem preconceitos de origem, raça, sexo, cor, idade e quaisquer outras formas de discriminação.",
    areas: ["direito constitucional", "direitos humanos"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-caput",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, caput",
    ementa: "Princípio da igualdade e direitos individuais",
    texto:
      "Todos são iguais perante a lei, sem distinção de qualquer natureza, garantindo-se aos brasileiros e aos estrangeiros residentes no País a inviolabilidade do direito à vida, à liberdade, à igualdade, à segurança e à propriedade, nos termos seguintes:",
    areas: ["direito constitucional", "direitos humanos"],
    sinonimos: ["isonomia", "direitos fundamentais"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-ii",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, II",
    ementa: "Princípio da legalidade",
    texto:
      "ninguém será obrigado a fazer ou deixar de fazer alguma coisa senão em virtude de lei;",
    areas: ["direito constitucional", "direito administrativo"],
    sinonimos: ["legalidade", "reserva legal"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-xxxv",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, XXXV",
    ementa: "Inafastabilidade da jurisdição",
    texto:
      "a lei não excluirá da apreciação do Poder Judiciário lesão ou ameaça a direito;",
    areas: ["direito constitucional", "direito processual civil"],
    sinonimos: ["acesso à justiça", "inafastabilidade do controle jurisdicional"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-liv",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, LIV",
    ementa: "Devido processo legal",
    texto:
      "ninguém será privado da liberdade ou de seus bens sem o devido processo legal;",
    areas: ["direito constitucional", "direito processual civil", "direito processual penal"],
    sinonimos: ["due process", "devido processo legal"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-lv",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, LV",
    ementa: "Contraditório e ampla defesa",
    texto:
      "aos litigantes, em processo judicial ou administrativo, e aos acusados em geral são assegurados o contraditório e ampla defesa, com os meios e recursos a ela inerentes;",
    areas: ["direito constitucional", "direito processual civil", "direito processual penal"],
    sinonimos: ["contraditório", "ampla defesa"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-lxiii",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, LXIII",
    ementa: "Direito ao silêncio do preso",
    texto:
      "o preso será informado de seus direitos, entre os quais o de permanecer calado, sendo-lhe assegurada a assistência da família e de advogado;",
    areas: ["direito constitucional", "direito processual penal", "direitos humanos"],
    sinonimos: ["direito ao silêncio", "nemo tenetur se detegere"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-lxviii",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, LXVIII",
    ementa: "Habeas corpus",
    texto:
      "conceder-se-á habeas corpus sempre que alguém sofrer ou se achar ameaçado de sofrer violência ou coação em sua liberdade de locomoção, por ilegalidade ou abuso de poder;",
    areas: ["direito constitucional", "direito processual penal", "direitos humanos"],
    sinonimos: ["habeas corpus", "remédio constitucional", "liberdade de locomoção"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-lxix",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, LXIX",
    ementa: "Mandado de segurança",
    texto:
      "conceder-se-á mandado de segurança para proteger direito líquido e certo, não amparado por habeas corpus ou habeas data, quando o responsável pela ilegalidade ou abuso de poder for autoridade pública ou agente de pessoa jurídica no exercício de atribuições do Poder Público;",
    areas: ["direito constitucional", "direito administrativo"],
    sinonimos: ["mandado de segurança", "remédio constitucional", "direito líquido e certo"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art37-caput",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 37, caput",
    ementa: "Princípios da Administração Pública",
    texto:
      "A administração pública direta e indireta de qualquer dos Poderes da União, dos Estados, do Distrito Federal e dos Municípios obedecerá aos princípios de legalidade, impessoalidade, moralidade, publicidade e eficiência e, também, ao seguinte:",
    areas: ["direito administrativo", "direito constitucional"],
    sinonimos: ["LIMPE", "princípios da administração pública"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art44",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 44",
    ementa: "Poder Legislativo e bicameralismo",
    texto:
      "O Poder Legislativo é exercido pelo Congresso Nacional, que se compõe da Câmara dos Deputados e do Senado Federal. Parágrafo único. Cada legislatura terá a duração de quatro anos.",
    areas: ["direito constitucional", "ciência política", "teoria geral do estado"],
    sinonimos: ["congresso nacional", "bicameralismo", "poder legislativo"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art59",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 59",
    ementa: "Espécies normativas do processo legislativo",
    texto:
      "O processo legislativo compreende a elaboração de: I - emendas à Constituição; II - leis complementares; III - leis ordinárias; IV - leis delegadas; V - medidas provisórias; VI - decretos legislativos; VII - resoluções. Parágrafo único. Lei complementar disporá sobre a elaboração, redação, alteração e consolidação das leis.",
    areas: ["direito constitucional", "ciência política"],
    sinonimos: ["processo legislativo", "espécies normativas", "hierarquia das normas"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art102-caput",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 102, caput",
    ementa: "Competência do Supremo Tribunal Federal",
    texto:
      "Compete ao Supremo Tribunal Federal, precipuamente, a guarda da Constituição, cabendo-lhe:",
    areas: ["direito constitucional"],
    sinonimos: ["STF", "controle de constitucionalidade", "guarda da constituição"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },

  // ---------------------------------------------------------------------
  // LINDB
  // ---------------------------------------------------------------------
  {
    id: "lindb-art3",
    tipo: "legislacao",
    norma: "Lei de Introdução às Normas do Direito Brasileiro (Decreto-Lei 4.657/1942)",
    siglaNorma: "LINDB",
    dispositivo: "Art. 3º",
    ementa: "Obrigatoriedade da lei",
    texto: "Ninguém se escusa de cumprir a lei, alegando que não a conhece.",
    areas: ["introdução ao estudo do direito", "direito civil"],
    sinonimos: ["ignorantia legis", "obrigatoriedade das leis"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del4657compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "lindb-art2",
    tipo: "legislacao",
    norma: "Lei de Introdução às Normas do Direito Brasileiro (Decreto-Lei 4.657/1942)",
    siglaNorma: "LINDB",
    dispositivo: "Art. 2º",
    ementa: "Vigência e revogação da lei",
    texto:
      "Não se destinando à vigência temporária, a lei terá vigor até que outra a modifique ou revogue.",
    areas: ["introdução ao estudo do direito", "direito civil"],
    sinonimos: ["vigência", "revogação", "princípio da continuidade"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del4657compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },

  // ---------------------------------------------------------------------
  // Código Civil
  // ---------------------------------------------------------------------
  {
    id: "cc-art1",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 1º",
    ementa: "Capacidade de direito",
    texto: "Toda pessoa é capaz de direitos e deveres na ordem civil.",
    areas: ["direito civil"],
    sinonimos: ["personalidade jurídica", "capacidade de direito"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art2",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 2º",
    ementa: "Início da personalidade civil e direitos do nascituro",
    texto:
      "A personalidade civil da pessoa começa do nascimento com vida; mas a lei põe a salvo, desde a concepção, os direitos do nascituro.",
    areas: ["direito civil"],
    sinonimos: ["nascituro", "início da personalidade", "teoria natalista"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art104",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 104",
    ementa: "Requisitos de validade do negócio jurídico",
    texto:
      "A validade do negócio jurídico requer: I - agente capaz; II - objeto lícito, possível, determinado ou determinável; III - forma prescrita ou não defesa em lei.",
    areas: ["direito civil"],
    sinonimos: ["negócio jurídico", "plano da validade", "escada ponteana"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art186",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 186",
    ementa: "Ato ilícito e responsabilidade subjetiva",
    texto:
      "Aquele que, por ação ou omissão voluntária, negligência ou imprudência, violar direito e causar dano a outrem, ainda que exclusivamente moral, comete ato ilícito.",
    areas: ["direito civil"],
    sinonimos: ["ato ilícito", "responsabilidade civil subjetiva", "culpa", "dano moral"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art187",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 187",
    ementa: "Abuso de direito",
    texto:
      "Também comete ato ilícito o titular de um direito que, ao exercê-lo, excede manifestamente os limites impostos pelo seu fim econômico ou social, pela boa-fé ou pelos bons costumes.",
    areas: ["direito civil"],
    sinonimos: ["abuso de direito", "boa-fé objetiva"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art205",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 205",
    ementa: "Prazo geral de prescrição",
    texto:
      "A prescrição ocorre em dez anos, quando a lei não lhe haja fixado prazo menor.",
    areas: ["direito civil"],
    sinonimos: ["prescrição decenal", "prazo prescricional geral"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art389",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 389",
    ementa: "Inadimplemento e perdas e danos",
    texto:
      "Não cumprida a obrigação, responde o devedor por perdas e danos, mais juros e atualização monetária segundo índices oficiais regularmente estabelecidos, e honorários de advogado.",
    areas: ["direito civil"],
    sinonimos: ["inadimplemento", "perdas e danos", "mora"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art422",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 422",
    ementa: "Boa-fé objetiva nos contratos",
    texto:
      "Os contratantes são obrigados a guardar, assim na conclusão do contrato, como em sua execução, os princípios de probidade e boa-fé.",
    areas: ["direito civil"],
    sinonimos: ["boa-fé objetiva", "probidade contratual"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art927",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 927",
    ementa: "Dever de reparar e responsabilidade objetiva pelo risco",
    texto:
      "Aquele que, por ato ilícito (arts. 186 e 187), causar dano a outrem, fica obrigado a repará-lo. Parágrafo único. Haverá obrigação de reparar o dano, independentemente de culpa, nos casos especificados em lei, ou quando a atividade normalmente desenvolvida pelo autor do dano implicar, por sua natureza, risco para os direitos de outrem.",
    areas: ["direito civil"],
    sinonimos: ["responsabilidade objetiva", "teoria do risco", "dever de indenizar"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },

  // ---------------------------------------------------------------------
  // Código de Processo Civil
  // ---------------------------------------------------------------------
  {
    id: "cpc-art1",
    tipo: "legislacao",
    norma: "Código de Processo Civil (Lei 13.105/2015)",
    siglaNorma: "CPC",
    dispositivo: "Art. 1º",
    ementa: "Interpretação conforme a Constituição",
    texto:
      "O processo civil será ordenado, disciplinado e interpretado conforme os valores e as normas fundamentais estabelecidos na Constituição da República Federativa do Brasil, observando-se as disposições deste Código.",
    areas: ["direito processual civil"],
    sinonimos: ["normas fundamentais do processo civil", "constitucionalização do processo"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cpc-art2",
    tipo: "legislacao",
    norma: "Código de Processo Civil (Lei 13.105/2015)",
    siglaNorma: "CPC",
    dispositivo: "Art. 2º",
    ementa: "Princípio dispositivo e impulso oficial",
    texto:
      "O processo começa por iniciativa da parte e se desenvolve por impulso oficial, salvo as exceções previstas em lei.",
    areas: ["direito processual civil"],
    sinonimos: ["princípio da inércia", "impulso oficial", "princípio dispositivo"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cpc-art10",
    tipo: "legislacao",
    norma: "Código de Processo Civil (Lei 13.105/2015)",
    siglaNorma: "CPC",
    dispositivo: "Art. 10",
    ementa: "Vedação à decisão surpresa",
    texto:
      "O juiz não pode decidir, em grau algum de jurisdição, com base em fundamento a respeito do qual não se tenha dado às partes oportunidade de se manifestar, ainda que se trate de matéria sobre a qual deva decidir de ofício.",
    areas: ["direito processual civil"],
    sinonimos: ["decisão surpresa", "contraditório substancial"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cpc-art300",
    tipo: "legislacao",
    norma: "Código de Processo Civil (Lei 13.105/2015)",
    siglaNorma: "CPC",
    dispositivo: "Art. 300",
    ementa: "Requisitos da tutela de urgência",
    texto:
      "A tutela de urgência será concedida quando houver elementos que evidenciem a probabilidade do direito e o perigo de dano ou o risco ao resultado útil do processo.",
    areas: ["direito processual civil"],
    sinonimos: ["tutela de urgência", "fumus boni iuris", "periculum in mora", "liminar"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cpc-art319",
    tipo: "legislacao",
    norma: "Código de Processo Civil (Lei 13.105/2015)",
    siglaNorma: "CPC",
    dispositivo: "Art. 319",
    ementa: "Requisitos da petição inicial",
    texto:
      "A petição inicial indicará: I - o juízo a que é dirigida; II - os nomes, os prenomes, o estado civil, a existência de união estável, a profissão, o número de inscrição no Cadastro de Pessoas Físicas ou no Cadastro Nacional da Pessoa Jurídica, o endereço eletrônico, o domicílio e a residência do autor e do réu; III - o fato e os fundamentos jurídicos do pedido; IV - o pedido com as suas especificações; V - o valor da causa; VI - as provas com que o autor pretende demonstrar a verdade dos fatos alegados; VII - a opção do autor pela realização ou não de audiência de conciliação ou de mediação.",
    areas: ["direito processual civil", "prática jurídica"],
    sinonimos: ["petição inicial", "requisitos da inicial", "peça processual"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },

  // ---------------------------------------------------------------------
  // Código Penal e Código de Processo Penal
  // ---------------------------------------------------------------------
  {
    id: "cp-art1",
    tipo: "legislacao",
    norma: "Código Penal (Decreto-Lei 2.848/1940)",
    siglaNorma: "CP",
    dispositivo: "Art. 1º",
    ementa: "Legalidade e anterioridade penal",
    texto:
      "Não há crime sem lei anterior que o defina. Não há pena sem prévia cominação legal.",
    areas: ["direito penal"],
    sinonimos: ["nullum crimen nulla poena sine lege", "anterioridade da lei penal", "legalidade penal"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cp-art121-caput",
    tipo: "legislacao",
    norma: "Código Penal (Decreto-Lei 2.848/1940)",
    siglaNorma: "CP",
    dispositivo: "Art. 121, caput",
    ementa: "Homicídio simples",
    texto: "Matar alguém: Pena - reclusão, de seis a vinte anos.",
    areas: ["direito penal"],
    sinonimos: ["homicídio", "crimes contra a vida"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cp-art155-caput",
    tipo: "legislacao",
    norma: "Código Penal (Decreto-Lei 2.848/1940)",
    siglaNorma: "CP",
    dispositivo: "Art. 155, caput",
    ementa: "Furto",
    texto:
      "Subtrair, para si ou para outrem, coisa alheia móvel: Pena - reclusão, de um a quatro anos, e multa.",
    areas: ["direito penal"],
    sinonimos: ["furto", "crimes contra o patrimônio"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cpp-art155",
    tipo: "legislacao",
    norma: "Código de Processo Penal (Decreto-Lei 3.689/1941)",
    siglaNorma: "CPP",
    dispositivo: "Art. 155",
    ementa: "Livre convencimento motivado e valor do inquérito",
    texto:
      "O juiz formará sua convicção pela livre apreciação da prova produzida em contraditório judicial, não podendo fundamentar sua decisão exclusivamente nos elementos informativos colhidos na investigação, ressalvadas as provas cautelares, não repetíveis e antecipadas.",
    areas: ["direito processual penal"],
    sinonimos: ["livre convencimento motivado", "valor probatório do inquérito"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },

  // ---------------------------------------------------------------------
  // Código de Defesa do Consumidor
  // ---------------------------------------------------------------------
  {
    id: "cdc-art2",
    tipo: "legislacao",
    norma: "Código de Defesa do Consumidor (Lei 8.078/1990)",
    siglaNorma: "CDC",
    dispositivo: "Art. 2º",
    ementa: "Conceito de consumidor",
    texto:
      "Consumidor é toda pessoa física ou jurídica que adquire ou utiliza produto ou serviço como destinatário final. Parágrafo único. Equipara-se a consumidor a coletividade de pessoas, ainda que indetermináveis, que haja intervindo nas relações de consumo.",
    areas: ["direito do consumidor", "direito civil"],
    sinonimos: ["consumidor", "destinatário final", "teoria finalista"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cdc-art3",
    tipo: "legislacao",
    norma: "Código de Defesa do Consumidor (Lei 8.078/1990)",
    siglaNorma: "CDC",
    dispositivo: "Art. 3º, caput",
    ementa: "Conceito de fornecedor",
    texto:
      "Fornecedor é toda pessoa física ou jurídica, pública ou privada, nacional ou estrangeira, bem como os entes despersonalizados, que desenvolvem atividade de produção, montagem, criação, construção, transformação, importação, exportação, distribuição ou comercialização de produtos ou prestação de serviços.",
    areas: ["direito do consumidor"],
    sinonimos: ["fornecedor", "relação de consumo"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cdc-art6-viii",
    tipo: "legislacao",
    norma: "Código de Defesa do Consumidor (Lei 8.078/1990)",
    siglaNorma: "CDC",
    dispositivo: "Art. 6º, VIII",
    ementa: "Inversão do ônus da prova",
    texto:
      "a facilitação da defesa de seus direitos, inclusive com a inversão do ônus da prova, a seu favor, no processo civil, quando, a critério do juiz, for verossímil a alegação ou quando for ele hipossuficiente, segundo as regras ordinárias de experiências;",
    areas: ["direito do consumidor", "direito processual civil"],
    sinonimos: ["inversão do ônus da prova", "hipossuficiência", "verossimilhança"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cdc-art14-caput",
    tipo: "legislacao",
    norma: "Código de Defesa do Consumidor (Lei 8.078/1990)",
    siglaNorma: "CDC",
    dispositivo: "Art. 14, caput",
    ementa: "Responsabilidade do fornecedor de serviços pelo fato do serviço",
    texto:
      "O fornecedor de serviços responde, independentemente da existência de culpa, pela reparação dos danos causados aos consumidores por defeitos relativos à prestação dos serviços, bem como por informações insuficientes ou inadequadas sobre sua fruição e riscos.",
    areas: ["direito do consumidor"],
    sinonimos: ["fato do serviço", "responsabilidade objetiva do fornecedor", "acidente de consumo"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cdc-art49",
    tipo: "legislacao",
    norma: "Código de Defesa do Consumidor (Lei 8.078/1990)",
    siglaNorma: "CDC",
    dispositivo: "Art. 49",
    ementa: "Direito de arrependimento",
    texto:
      "O consumidor pode desistir do contrato, no prazo de 7 dias a contar de sua assinatura ou do ato de recebimento do produto ou serviço, sempre que a contratação de fornecimento de produtos e serviços ocorrer fora do estabelecimento comercial, especialmente por telefone ou a domicílio.",
    areas: ["direito do consumidor"],
    sinonimos: ["direito de arrependimento", "prazo de reflexão", "compra online"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },

  // ---------------------------------------------------------------------
  // CLT
  // ---------------------------------------------------------------------
  {
    id: "clt-art3",
    tipo: "legislacao",
    norma: "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
    siglaNorma: "CLT",
    dispositivo: "Art. 3º",
    ementa: "Conceito de empregado",
    texto:
      "Considera-se empregado toda pessoa física que prestar serviços de natureza não eventual a empregador, sob a dependência deste e mediante salário.",
    areas: ["direito do trabalho"],
    sinonimos: ["vínculo empregatício", "subordinação", "pessoalidade", "onerosidade"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "clt-art2",
    tipo: "legislacao",
    norma: "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
    siglaNorma: "CLT",
    dispositivo: "Art. 2º, caput",
    ementa: "Conceito de empregador",
    texto:
      "Considera-se empregador a empresa, individual ou coletiva, que, assumindo os riscos da atividade econômica, admite, assalaria e dirige a prestação pessoal de serviço.",
    areas: ["direito do trabalho"],
    sinonimos: ["alteridade", "risco da atividade econômica", "poder diretivo"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "clt-art4",
    tipo: "legislacao",
    norma: "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
    siglaNorma: "CLT",
    dispositivo: "Art. 4º, caput",
    ementa: "Tempo à disposição do empregador",
    texto:
      "Considera-se como de serviço efetivo o período em que o empregado esteja à disposição do empregador, aguardando ou executando ordens, salvo disposição especial expressamente consignada.",
    areas: ["direito do trabalho"],
    sinonimos: ["sobreaviso", "prontidão", "serviço efetivo"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "clt-art58",
    tipo: "legislacao",
    norma: "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
    siglaNorma: "CLT",
    dispositivo: "Art. 58, caput",
    ementa: "Duração normal da jornada de trabalho",
    texto:
      "A duração normal do trabalho, para os empregados em qualquer atividade privada, não excederá de 8 (oito) horas diárias, desde que não seja fixado expressamente outro limite.",
    areas: ["direito do trabalho"],
    sinonimos: ["jornada de oito horas", "limite diário"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "clt-art59",
    tipo: "legislacao",
    norma: "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
    siglaNorma: "CLT",
    dispositivo: "Art. 59, caput e § 1º",
    ementa: "Horas extras e adicional mínimo de cinquenta por cento",
    texto:
      "A duração diária do trabalho poderá ser acrescida de horas extras, em número não excedente de duas, por acordo individual, convenção coletiva ou acordo coletivo de trabalho. § 1º A remuneração da hora extra será, pelo menos, 50% (cinquenta por cento) superior à da hora normal.",
    areas: ["direito do trabalho"],
    sinonimos: ["hora suplementar", "adicional de horas extras", "acordo individual escrito"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "clt-art71",
    tipo: "legislacao",
    norma: "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
    siglaNorma: "CLT",
    dispositivo: "Art. 71, caput e §§ 1º e 2º",
    ementa: "Intervalo intrajornada para repouso e alimentação",
    texto:
      "Em qualquer trabalho contínuo, cuja duração exceda de 6 (seis) horas, é obrigatória a concessão de um intervalo para repouso ou alimentação, o qual será, no mínimo, de 1 (uma) hora e, salvo acordo escrito ou contrato coletivo em contrário, não poderá exceder de 2 (duas) horas. § 1º Não excedendo de 6 (seis) horas o trabalho, será, entretanto, obrigatório um intervalo de 15 (quinze) minutos quando a duração ultrapassar 4 (quatro) horas. § 2º Os intervalos de descanso não serão computados na duração do trabalho.",
    areas: ["direito do trabalho"],
    sinonimos: ["intervalo intrajornada", "horário de almoço", "descanso"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "clt-art129",
    tipo: "legislacao",
    norma: "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
    siglaNorma: "CLT",
    dispositivo: "Art. 129",
    ementa: "Direito anual ao gozo de férias",
    texto:
      "Todo empregado terá direito anualmente ao gozo de um período de férias, sem prejuízo da remuneração.",
    areas: ["direito do trabalho"],
    sinonimos: ["férias remuneradas", "período aquisitivo"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "clt-art442",
    tipo: "legislacao",
    norma: "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
    siglaNorma: "CLT",
    dispositivo: "Art. 442, caput",
    ementa: "Contrato individual de trabalho",
    texto:
      "Contrato individual de trabalho é o acordo tácito ou expresso, correspondente à relação de emprego.",
    areas: ["direito do trabalho"],
    sinonimos: ["ajuste tácito", "primazia da realidade", "relação de emprego"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "clt-art477",
    tipo: "legislacao",
    norma: "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
    siglaNorma: "CLT",
    dispositivo: "Art. 477, caput",
    ementa: "Obrigações do empregador na extinção do contrato",
    texto:
      "Na extinção do contrato de trabalho, o empregador deverá proceder à anotação na Carteira de Trabalho e Previdência Social, comunicar a dispensa aos órgãos competentes e realizar o pagamento das verbas rescisórias no prazo e na forma estabelecidos neste artigo.",
    areas: ["direito do trabalho"],
    sinonimos: ["verbas rescisórias", "baixa na carteira", "acerto rescisório"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "clt-art482",
    tipo: "legislacao",
    norma: "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
    siglaNorma: "CLT",
    dispositivo: "Art. 482, caput e alíneas",
    ementa: "Justa causa para dispensa pelo empregador",
    texto:
      "Constituem justa causa para rescisão do contrato de trabalho pelo empregador: a) ato de improbidade; b) incontinência de conduta ou mau procedimento; c) negociação habitual por conta própria ou alheia sem permissão do empregador, e quando constituir ato de concorrência à empresa para a qual trabalha o empregado, ou for prejudicial ao serviço; d) condenação criminal do empregado, passada em julgado, caso não tenha havido suspensão da execução da pena; e) desídia no desempenho das respectivas funções; f) embriaguez habitual ou em serviço; g) violação de segredo da empresa; h) ato de indisciplina ou de insubordinação; i) abandono de emprego; j) ato lesivo da honra ou da boa fama praticado no serviço contra qualquer pessoa, ou ofensas físicas, nas mesmas condições, salvo em caso de legítima defesa, própria ou de outrem; k) ato lesivo da honra ou da boa fama ou ofensas físicas praticadas contra o empregador e superiores hierárquicos, salvo em caso de legítima defesa, própria ou de outrem; l) prática constante de jogos de azar; m) perda da habilitação ou dos requisitos estabelecidos em lei para o exercício da profissão, em decorrência de conduta dolosa do empregado.",
    areas: ["direito do trabalho"],
    sinonimos: ["demissão por justa causa", "desídia", "abandono de emprego", "insubordinação"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "clt-art483",
    tipo: "legislacao",
    norma: "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
    siglaNorma: "CLT",
    dispositivo: "Art. 483, caput e alíneas",
    ementa: "Rescisão indireta por falta do empregador",
    texto:
      "O empregado poderá considerar rescindido o contrato e pleitear a devida indenização quando: a) forem exigidos serviços superiores às suas forças, defesos por lei, contrários aos bons costumes, ou alheios ao contrato; b) for tratado pelo empregador ou por seus superiores hierárquicos com rigor excessivo; c) correr perigo manifesto de mal considerável; d) não cumprir o empregador as obrigações do contrato; e) praticar o empregador ou seus prepostos, contra ele ou pessoas de sua família, ato lesivo da honra e boa fama; f) o empregador ou seus prepostos ofenderem-no fisicamente, salvo em caso de legítima defesa, própria ou de outrem; g) o empregador reduzir o seu trabalho, sendo este por peça ou tarefa, de forma a afetar sensivelmente a importância dos salários.",
    areas: ["direito do trabalho"],
    sinonimos: ["rescisão indireta", "justa causa do empregador", "despedida indireta"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "clt-art611a",
    tipo: "legislacao",
    norma: "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
    siglaNorma: "CLT",
    dispositivo: "Art. 611-A, caput",
    ementa: "Prevalência do negociado coletivo sobre o legislado",
    texto:
      "A convenção coletiva e o acordo coletivo de trabalho têm prevalência sobre a lei quando, entre outros, dispuserem sobre:",
    areas: ["direito do trabalho"],
    sinonimos: ["negociado sobre o legislado", "convenção coletiva", "acordo coletivo"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },

  // ---------------------------------------------------------------------
  // Código Tributário Nacional
  // ---------------------------------------------------------------------
  {
    id: "ctn-art3",
    tipo: "legislacao",
    norma: "Código Tributário Nacional (Lei 5.172/1966)",
    siglaNorma: "CTN",
    dispositivo: "Art. 3º",
    ementa: "Definição legal de tributo",
    texto:
      "Tributo é toda prestação pecuniária compulsória, em moeda ou cujo valor nela se possa exprimir, que não constitua sanção de ato ilícito, instituída em lei e cobrada mediante atividade administrativa plenamente vinculada.",
    areas: ["direito tributário"],
    sinonimos: ["conceito de tributo", "prestação pecuniária compulsória", "atividade vinculada"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l5172compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "ctn-art97",
    tipo: "legislacao",
    norma: "Código Tributário Nacional (Lei 5.172/1966)",
    siglaNorma: "CTN",
    dispositivo: "Art. 97",
    ementa: "Reserva legal em matéria tributária",
    texto:
      "Sòmente a lei pode estabelecer: I - a instituição de tributos, ou a sua extinção; II - a majoração de tributos, ou sua redução, ressalvado o disposto nos arts. 21, 26, 39, 57 e 65; III - a definição do fato gerador da obrigação tributária principal, ressalvado o disposto no inciso I do § 3º do art. 52, e do seu sujeito passivo; IV - a fixação de alíquota do tributo e da sua base de cálculo, ressalvado o disposto nos arts. 21, 26, 39, 57 e 65; V - a cominação de penalidades para as ações ou omissões contrárias a seus dispositivos, ou para outras infrações nela definidas; VI - as hipóteses de exclusão, suspensão e extinção de créditos tributários, ou de dispensa ou redução de penalidades. § 1º Equipara-se à majoração do tributo a modificação da sua base de cálculo, que importe em torná-lo mais oneroso. § 2º Não constitui majoração de tributo, para os fins do disposto no inciso II dêste artigo, a atualização do valor monetário da respectiva base de cálculo.",
    areas: ["direito tributário", "direito constitucional"],
    sinonimos: ["legalidade tributária", "reserva de lei", "majoração de alíquota"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l5172compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "ctn-art113",
    tipo: "legislacao",
    norma: "Código Tributário Nacional (Lei 5.172/1966)",
    siglaNorma: "CTN",
    dispositivo: "Art. 113",
    ementa: "Obrigação tributária principal e acessória",
    texto:
      "A obrigação tributária é principal ou acessória. § 1º A obrigação principal surge com a ocorrência do fato gerador, tem por objeto o pagamento de tributo ou penalidade pecuniária e extingue-se juntamente com o crédito dela decorrente. § 2º A obrigação acessória decorre da legislação tributária e tem por objeto as prestações, positivas ou negativas, nela previstas no interêsse da arrecadação ou da fiscalização dos tributos. § 3º A obrigação acessória, pelo simples fato da sua inobservância, converte-se em obrigação principal relativamente à penalidade pecuniária.",
    areas: ["direito tributário"],
    sinonimos: ["dever instrumental", "penalidade pecuniária", "obrigação acessória"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l5172compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "ctn-art114",
    tipo: "legislacao",
    norma: "Código Tributário Nacional (Lei 5.172/1966)",
    siglaNorma: "CTN",
    dispositivo: "Art. 114",
    ementa: "Fato gerador da obrigação principal",
    texto:
      "Fato gerador da obrigação principal é a situação definida em lei como necessária e suficiente à sua ocorrência.",
    areas: ["direito tributário"],
    sinonimos: ["hipótese de incidência", "subsunção tributária"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l5172compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "ctn-art142",
    tipo: "legislacao",
    norma: "Código Tributário Nacional (Lei 5.172/1966)",
    siglaNorma: "CTN",
    dispositivo: "Art. 142",
    ementa: "Lançamento e constituição do crédito tributário",
    texto:
      "Compete privativamente à autoridade administrativa constituir o crédito tributário pelo lançamento, assim entendido o procedimento administrativo tendente a verificar a ocorrência do fato gerador da obrigação correspondente, determinar a matéria tributável, calcular o montante do tributo devido, identificar o sujeito passivo e, sendo caso, propor a aplicação da penalidade cabível. Parágrafo único. A atividade administrativa de lançamento é vinculada e obrigatória, sob pena de responsabilidade funcional.",
    areas: ["direito tributário", "direito administrativo"],
    sinonimos: ["lançamento tributário", "atividade vinculada e obrigatória"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l5172compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "ctn-art156",
    tipo: "legislacao",
    norma: "Código Tributário Nacional (Lei 5.172/1966)",
    siglaNorma: "CTN",
    dispositivo: "Art. 156",
    ementa: "Modalidades de extinção do crédito tributário",
    texto:
      "Extinguem o crédito tributário: I - o pagamento; II - a compensação; III - a transação; IV - remissão; V - a prescrição e a decadência; VI - a conversão de depósito em renda; VII - o pagamento antecipado e a homologação do lançamento nos termos do disposto no artigo 150 e seus §§ 1º e 4º; VIII - a consignação em pagamento, nos termos do disposto no § 2º do artigo 164; IX - a decisão administrativa irreformável, assim entendida a definitiva na órbita administrativa, que não mais possa ser objeto de ação anulatória; X - a decisão judicial passada em julgado; XI – a dação em pagamento em bens imóveis, na forma e condições estabelecidas em lei.",
    areas: ["direito tributário"],
    sinonimos: ["pagamento", "compensação", "dação em pagamento", "remissão"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l5172compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "ctn-art173",
    tipo: "legislacao",
    norma: "Código Tributário Nacional (Lei 5.172/1966)",
    siglaNorma: "CTN",
    dispositivo: "Art. 173",
    ementa: "Decadência do direito de constituir o crédito",
    texto:
      "O direito de a Fazenda Pública constituir o crédito tributário extingue-se após 5 (cinco) anos, contados: I - do primeiro dia do exercício seguinte àquele em que o lançamento poderia ter sido efetuado; II - da data em que se tornar definitiva a decisão que houver anulado, por vício formal, o lançamento anteriormente efetuado. Parágrafo único. O direito a que se refere êste artigo extingue-se definitivamente com o decurso do prazo nêle previsto, contado da data em que tenha sido iniciada a constituição do crédito tributário pela notificação, ao sujeito passivo, de qualquer medida preparatória indispensável ao lançamento.",
    areas: ["direito tributário"],
    sinonimos: ["decadência tributária", "prazo de cinco anos", "caducidade do lançamento"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l5172compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "ctn-art174",
    tipo: "legislacao",
    norma: "Código Tributário Nacional (Lei 5.172/1966)",
    siglaNorma: "CTN",
    dispositivo: "Art. 174",
    ementa: "Prescrição da cobrança do crédito tributário",
    texto:
      "A ação para a cobrança do crédito tributário prescreve em cinco anos, contados da data da sua constituição definitiva. Parágrafo único. A prescrição se interrompe: I – pelo despacho do juiz que ordenar a citação em execução fiscal; II - pelo protesto judicial ou extrajudicial; III - por qualquer ato judicial que constitua em mora o devedor; IV - por qualquer ato inequívoco ainda que extrajudicial, que importe em reconhecimento do débito pelo devedor.",
    areas: ["direito tributário", "direito processual civil"],
    sinonimos: ["prescrição tributária", "execução fiscal", "interrupção do prazo"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l5172compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },

  // ---------------------------------------------------------------------
  // Estatuto da Advocacia e da OAB
  // ---------------------------------------------------------------------
  {
    id: "eoab-art1",
    tipo: "legislacao",
    norma: "Estatuto da Advocacia e da OAB (Lei 8.906/1994)",
    siglaNorma: "EAOAB",
    dispositivo: "Art. 1º",
    ementa: "Atividades privativas de advocacia",
    texto:
      "São atividades privativas de advocacia: I - a postulação a qualquer órgão do Poder Judiciário e aos juizados especiais; II - as atividades de consultoria, assessoria e direção jurídicas. § 1º Não se inclui na atividade privativa de advocacia a impetração de habeas corpus em qualquer instância ou tribunal. § 2º Os atos e contratos constitutivos de pessoas jurídicas, sob pena de nulidade, só podem ser admitidos a registro, nos órgãos competentes, quando visados por advogados. § 3º É vedada a divulgação de advocacia em conjunto com outra atividade.",
    areas: ["advocacia", "ética profissional"],
    sinonimos: ["postulação", "consultoria jurídica", "atividade privativa", "capacidade postulatória"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8906.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "eoab-art2",
    tipo: "legislacao",
    norma: "Estatuto da Advocacia e da OAB (Lei 8.906/1994)",
    siglaNorma: "EAOAB",
    dispositivo: "Art. 2º",
    ementa: "Advogado indispensável à administração da justiça",
    texto:
      "O advogado é indispensável à administração da justiça. § 1º No seu ministério privado, o advogado presta serviço público e exerce função social. § 2º No processo judicial, o advogado contribui, na postulação de decisão favorável ao seu constituinte, ao convencimento do julgador, e seus atos constituem múnus público. § 2º-A. No processo administrativo, o advogado contribui com a postulação de decisão favorável ao seu constituinte, e os seus atos constituem múnus público. § 3º No exercício da profissão, o advogado é inviolável por seus atos e manifestações, nos limites desta lei.",
    areas: ["advocacia", "ética profissional", "direito constitucional"],
    sinonimos: ["múnus público", "imunidade profissional", "função social do advogado"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8906.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "eoab-art7-ii",
    tipo: "legislacao",
    norma: "Estatuto da Advocacia e da OAB (Lei 8.906/1994)",
    siglaNorma: "EAOAB",
    dispositivo: "Art. 7º, II",
    ementa: "Inviolabilidade do escritório e dos instrumentos de trabalho",
    texto:
      "a inviolabilidade de seu escritório ou local de trabalho, bem como de seus instrumentos de trabalho, de sua correspondência escrita, eletrônica, telefônica e telemática, desde que relativas ao exercício da advocacia;",
    areas: ["advocacia", "direito constitucional", "direito processual penal"],
    sinonimos: ["prerrogativa profissional", "sigilo profissional", "busca e apreensão em escritório"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8906.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "eoab-art22",
    tipo: "legislacao",
    norma: "Estatuto da Advocacia e da OAB (Lei 8.906/1994)",
    siglaNorma: "EAOAB",
    dispositivo: "Art. 22, caput",
    ementa: "Honorários convencionados, arbitrados e de sucumbência",
    texto:
      "A prestação de serviço profissional assegura aos inscritos na OAB o direito aos honorários convencionados, aos fixados por arbitramento judicial e aos de sucumbência.",
    areas: ["advocacia", "direito processual civil"],
    sinonimos: ["honorários advocatícios", "sucumbência", "arbitramento judicial"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8906.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "eoab-art31",
    tipo: "legislacao",
    norma: "Estatuto da Advocacia e da OAB (Lei 8.906/1994)",
    siglaNorma: "EAOAB",
    dispositivo: "Art. 31",
    ementa: "Dever de independência e prestígio da classe",
    texto:
      "O advogado deve proceder de forma que o torne merecedor de respeito e que contribua para o prestígio da classe e da advocacia. § 1º O advogado, no exercício da profissão, deve manter independência em qualquer circunstância. § 2º Nenhum receio de desagradar a magistrado ou a qualquer autoridade, nem de incorrer em impopularidade, deve deter o advogado no exercício da profissão.",
    areas: ["advocacia", "ética profissional"],
    sinonimos: ["independência do advogado", "deveres éticos", "conduta profissional"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8906.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "eoab-art32",
    tipo: "legislacao",
    norma: "Estatuto da Advocacia e da OAB (Lei 8.906/1994)",
    siglaNorma: "EAOAB",
    dispositivo: "Art. 32",
    ementa: "Responsabilidade do advogado por dolo ou culpa",
    texto:
      "O advogado é responsável pelos atos que, no exercício profissional, praticar com dolo ou culpa. Parágrafo único. Em caso de lide temerária, o advogado será solidariamente responsável com seu cliente, desde que coligado com este para lesar a parte contrária, o que será apurado em ação própria.",
    areas: ["advocacia", "ética profissional", "direito civil"],
    sinonimos: ["lide temerária", "responsabilidade profissional", "erro do advogado"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8906.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },

  // ---------------------------------------------------------------------
  // Previdência Social — Lei de Benefícios
  // ---------------------------------------------------------------------
  {
    id: "l8213-art25",
    tipo: "legislacao",
    norma: "Lei de Benefícios da Previdência Social (Lei 8.213/1991)",
    siglaNorma: "Lei 8.213/1991",
    dispositivo: "Art. 25",
    ementa: "Períodos de carência das prestações previdenciárias",
    texto:
      "A concessão das prestações pecuniárias do Regime Geral de Previdência Social depende dos seguintes períodos de carência, ressalvado o disposto no art. 26: I - auxílio-doença e aposentadoria por invalidez: 12 (doze) contribuições mensais; II - aposentadoria por idade, aposentadoria por tempo de serviço e aposentadoria especial: 180 contribuições mensais; III - salário-maternidade para as seguradas de que tratam os incisos V e VII do caput do art. 11 e o art. 13 desta Lei: 10 (dez) contribuições mensais, respeitado o disposto no parágrafo único do art. 39 desta Lei; e IV - auxílio-reclusão: 24 (vinte e quatro) contribuições mensais.",
    areas: ["direito previdenciário"],
    sinonimos: ["carência previdenciária", "contribuições mensais", "tempo mínimo de contribuição"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8213compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l8213-art26",
    tipo: "legislacao",
    norma: "Lei de Benefícios da Previdência Social (Lei 8.213/1991)",
    siglaNorma: "Lei 8.213/1991",
    dispositivo: "Art. 26, caput e I",
    ementa: "Benefícios que independem de carência",
    texto:
      "Independe de carência a concessão das seguintes prestações: I - pensão por morte, salário-família e auxílio-acidente;",
    areas: ["direito previdenciário"],
    sinonimos: ["dispensa de carência", "benefício sem carência"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8213compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l8213-art42",
    tipo: "legislacao",
    norma: "Lei de Benefícios da Previdência Social (Lei 8.213/1991)",
    siglaNorma: "Lei 8.213/1991",
    dispositivo: "Art. 42, caput",
    ementa: "Aposentadoria por invalidez",
    texto:
      "A aposentadoria por invalidez, uma vez cumprida, quando for o caso, a carência exigida, será devida ao segurado que, estando ou não em gozo de auxílio-doença, for considerado incapaz e insusceptível de reabilitação para o exercício de atividade que lhe garanta a subsistência, e ser-lhe-á paga enquanto permanecer nesta condição.",
    areas: ["direito previdenciário"],
    sinonimos: ["incapacidade permanente", "perícia médica", "reabilitação profissional"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8213compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l8213-art59",
    tipo: "legislacao",
    norma: "Lei de Benefícios da Previdência Social (Lei 8.213/1991)",
    siglaNorma: "Lei 8.213/1991",
    dispositivo: "Art. 59, caput",
    ementa: "Auxílio-doença por incapacidade temporária",
    texto:
      "O auxílio-doença será devido ao segurado que, havendo cumprido, quando for o caso, o período de carência exigido nesta Lei, ficar incapacitado para o seu trabalho ou para a sua atividade habitual por mais de 15 (quinze) dias consecutivos.",
    areas: ["direito previdenciário"],
    sinonimos: ["incapacidade temporária", "quinze dias", "afastamento por doença"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8213compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l8213-art74",
    tipo: "legislacao",
    norma: "Lei de Benefícios da Previdência Social (Lei 8.213/1991)",
    siglaNorma: "Lei 8.213/1991",
    dispositivo: "Art. 74, caput e incisos",
    ementa: "Pensão por morte e termo inicial do benefício",
    texto:
      "A pensão por morte será devida ao conjunto dos dependentes do segurado que falecer, aposentado ou não, a contar da data: I - do óbito, quando requerida em até 180 (cento e oitenta) dias após o óbito, para os filhos menores de 16 (dezesseis) anos, ou em até 90 (noventa) dias após o óbito, para os demais dependentes; II - do requerimento, quando requerida após o prazo previsto no inciso anterior; III - da decisão judicial, no caso de morte presumida.",
    areas: ["direito previdenciário"],
    sinonimos: ["pensão por morte", "dependentes", "morte presumida"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8213compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l8213-art86",
    tipo: "legislacao",
    norma: "Lei de Benefícios da Previdência Social (Lei 8.213/1991)",
    siglaNorma: "Lei 8.213/1991",
    dispositivo: "Art. 86, caput",
    ementa: "Auxílio-acidente como indenização por sequela",
    texto:
      "O auxílio-acidente será concedido, como indenização, ao segurado quando, após consolidação das lesões decorrentes de acidente de qualquer natureza, resultarem seqüelas que impliquem redução da capacidade para o trabalho que habitualmente exercia.",
    areas: ["direito previdenciário"],
    sinonimos: ["auxílio-acidente", "sequela", "redução da capacidade laborativa"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8213compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l8213-art103",
    tipo: "legislacao",
    norma: "Lei de Benefícios da Previdência Social (Lei 8.213/1991)",
    siglaNorma: "Lei 8.213/1991",
    dispositivo: "Art. 103, caput",
    ementa: "Decadência para revisão de benefício previdenciário",
    texto:
      "O prazo de decadência do direito ou da ação do segurado ou beneficiário para a revisão do ato de concessão, indeferimento, cancelamento ou cessação de benefício e do ato de deferimento, indeferimento ou não concessão de revisão de benefício é de 10 (dez) anos, contado:",
    areas: ["direito previdenciário"],
    sinonimos: ["revisão de benefício", "prazo decadencial", "dez anos"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8213compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },

  // ---------------------------------------------------------------------
  // Meio ambiente — Política Nacional e crimes ambientais
  // ---------------------------------------------------------------------
  {
    id: "l6938-art2",
    tipo: "legislacao",
    norma: "Política Nacional do Meio Ambiente (Lei 6.938/1981)",
    siglaNorma: "Lei 6.938/1981",
    dispositivo: "Art. 2º, caput e I",
    ementa: "Objetivo da Política Nacional do Meio Ambiente",
    texto:
      "A Política Nacional do Meio Ambiente tem por objetivo a preservação, melhoria e recuperação da qualidade ambiental propícia à vida, visando assegurar, no País, condições ao desenvolvimento sócio-econômico, aos interesses da segurança nacional e à proteção da dignidade da vida humana, atendidos os seguintes princípios: I - ação governamental na manutenção do equilíbrio ecológico, considerando o meio ambiente como um patrimônio público a ser necessariamente assegurado e protegido, tendo em vista o uso coletivo;",
    areas: ["direito ambiental"],
    sinonimos: ["equilíbrio ecológico", "patrimônio público ambiental", "desenvolvimento sustentável"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l6938.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l6938-art3-iii",
    tipo: "legislacao",
    norma: "Política Nacional do Meio Ambiente (Lei 6.938/1981)",
    siglaNorma: "Lei 6.938/1981",
    dispositivo: "Art. 3º, III",
    ementa: "Conceito legal de poluição",
    texto:
      "poluição, a degradação da qualidade ambiental resultante de atividades que direta ou indiretamente: a) prejudiquem a saúde, a segurança e o bem-estar da população; b) criem condições adversas às atividades sociais e econômicas; c) afetem desfavoravelmente a biota; d) afetem as condições estéticas ou sanitárias do meio ambiente; e) lancem matérias ou energia em desacordo com os padrões ambientais estabelecidos;",
    areas: ["direito ambiental"],
    sinonimos: ["poluição", "degradação ambiental", "padrões ambientais"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l6938.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l6938-art3-iv",
    tipo: "legislacao",
    norma: "Política Nacional do Meio Ambiente (Lei 6.938/1981)",
    siglaNorma: "Lei 6.938/1981",
    dispositivo: "Art. 3º, IV",
    ementa: "Conceito legal de poluidor",
    texto:
      "poluidor, a pessoa física ou jurídica, de direito público ou privado, responsável, direta ou indiretamente, por atividade causadora de degradação ambiental;",
    areas: ["direito ambiental"],
    sinonimos: ["poluidor direto e indireto", "responsável pela degradação"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l6938.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l6938-art14-p1",
    tipo: "legislacao",
    norma: "Política Nacional do Meio Ambiente (Lei 6.938/1981)",
    siglaNorma: "Lei 6.938/1981",
    dispositivo: "Art. 14, § 1º",
    ementa: "Responsabilidade civil objetiva por dano ambiental",
    texto:
      "Sem obstar a aplicação das penalidades previstas neste artigo, é o poluidor obrigado, independentemente da existência de culpa, a indenizar ou reparar os danos causados ao meio ambiente e a terceiros, afetados por sua atividade. O Ministério Público da União e dos Estados terá legitimidade para propor ação de responsabilidade civil e criminal, por danos causados ao meio ambiente.",
    areas: ["direito ambiental", "direito civil"],
    sinonimos: [
      "responsabilidade objetiva ambiental",
      "independentemente de culpa",
      "reparação do dano ambiental",
      "poluidor",
      "dano ambiental",
    ],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l6938.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l9605-art2",
    tipo: "legislacao",
    norma: "Lei de Crimes Ambientais (Lei 9.605/1998)",
    siglaNorma: "Lei 9.605/1998",
    dispositivo: "Art. 2º",
    ementa: "Concurso de pessoas nos crimes ambientais",
    texto:
      "Quem, de qualquer forma, concorre para a prática dos crimes previstos nesta Lei, incide nas penas a estes cominadas, na medida da sua culpabilidade, bem como o diretor, o administrador, o membro de conselho e de órgão técnico, o auditor, o gerente, o preposto ou mandatário de pessoa jurídica, que, sabendo da conduta criminosa de outrem, deixar de impedir a sua prática, quando podia agir para evitá-la.",
    areas: ["direito ambiental", "direito penal"],
    sinonimos: ["concurso de agentes", "omissão do administrador", "dever de agir"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9605.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l9605-art3",
    tipo: "legislacao",
    norma: "Lei de Crimes Ambientais (Lei 9.605/1998)",
    siglaNorma: "Lei 9.605/1998",
    dispositivo: "Art. 3º",
    ementa: "Responsabilidade penal da pessoa jurídica",
    texto:
      "As pessoas jurídicas serão responsabilizadas administrativa, civil e penalmente conforme o disposto nesta Lei, nos casos em que a infração seja cometida por decisão de seu representante legal ou contratual, ou de seu órgão colegiado, no interesse ou benefício da sua entidade. Parágrafo único. A responsabilidade das pessoas jurídicas não exclui a das pessoas físicas, autoras, co-autoras ou partícipes do mesmo fato.",
    areas: ["direito ambiental", "direito penal", "direito empresarial"],
    sinonimos: ["responsabilização da empresa", "dupla imputação", "órgão colegiado"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9605.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l9605-art21",
    tipo: "legislacao",
    norma: "Lei de Crimes Ambientais (Lei 9.605/1998)",
    siglaNorma: "Lei 9.605/1998",
    dispositivo: "Art. 21",
    ementa: "Penas aplicáveis à pessoa jurídica",
    texto:
      "As penas aplicáveis isolada, cumulativa ou alternativamente às pessoas jurídicas, de acordo com o disposto no art. 3º, são: I - multa; II - restritivas de direitos; III - prestação de serviços à comunidade.",
    areas: ["direito ambiental", "direito penal"],
    sinonimos: ["multa", "restritiva de direitos", "prestação de serviços à comunidade"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9605.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l9605-art54",
    tipo: "legislacao",
    norma: "Lei de Crimes Ambientais (Lei 9.605/1998)",
    siglaNorma: "Lei 9.605/1998",
    dispositivo: "Art. 54, caput e § 1º",
    ementa: "Crime de poluição",
    texto:
      "Causar poluição de qualquer natureza em níveis tais que resultem ou possam resultar em danos à saúde humana, ou que provoquem a mortandade de animais ou a destruição significativa da flora: Pena - reclusão, de um a quatro anos, e multa. § 1º Se o crime é culposo: Pena - detenção, de seis meses a um ano, e multa.",
    areas: ["direito ambiental", "direito penal"],
    sinonimos: ["crime de poluição", "mortandade de animais", "poluição culposa"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9605.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "l9605-art60",
    tipo: "legislacao",
    norma: "Lei de Crimes Ambientais (Lei 9.605/1998)",
    siglaNorma: "Lei 9.605/1998",
    dispositivo: "Art. 60, caput",
    ementa: "Atividade potencialmente poluidora sem licença ambiental",
    texto:
      "Construir, reformar, ampliar, instalar ou fazer funcionar, em qualquer parte do território nacional, estabelecimentos, obras ou serviços potencialmente poluidores, sem licença ou autorização dos órgãos ambientais competentes, ou contrariando as normas legais e regulamentares pertinentes: Pena - detenção, de 6 (seis) meses a 2 (dois) anos, ou multa, ou ambas as penas, cumulativamente.",
    areas: ["direito ambiental", "direito penal", "direito administrativo"],
    sinonimos: ["licenciamento ambiental", "operar sem licença", "autorização ambiental"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9605.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },

  // ---------------------------------------------------------------------
  // Sociedades por Ações
  // ---------------------------------------------------------------------
  {
    id: "lsa-art1",
    tipo: "legislacao",
    norma: "Lei das Sociedades por Ações (Lei 6.404/1976)",
    siglaNorma: "LSA",
    dispositivo: "Art. 1º",
    ementa: "Companhia e limitação da responsabilidade do acionista",
    texto:
      "A companhia ou sociedade anônima terá o capital dividido em ações, e a responsabilidade dos sócios ou acionistas será limitada ao preço de emissão das ações subscritas ou adquiridas.",
    areas: ["direito empresarial", "direito societário"],
    sinonimos: ["sociedade anônima", "capital social", "responsabilidade limitada"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l6404consol.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "lsa-art109",
    tipo: "legislacao",
    norma: "Lei das Sociedades por Ações (Lei 6.404/1976)",
    siglaNorma: "LSA",
    dispositivo: "Art. 109, caput",
    ementa: "Direitos essenciais do acionista",
    texto:
      "Nem o estatuto social nem a assembléia-geral poderão privar o acionista dos direitos de: I - participar dos lucros sociais; II - participar do acervo da companhia, em caso de liquidação; III - fiscalizar, na forma prevista nesta Lei, a gestão dos negócios sociais; IV - preferência para a subscrição de ações, partes beneficiárias conversíveis em ações, debêntures conversíveis em ações e bônus de subscrição, observado o disposto nos artigos 171 e 172; V - retirar-se da sociedade nos casos previstos nesta Lei.",
    areas: ["direito empresarial", "direito societário"],
    sinonimos: ["direitos essenciais", "direito de retirada", "participação nos lucros"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l6404consol.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "lsa-art115",
    tipo: "legislacao",
    norma: "Lei das Sociedades por Ações (Lei 6.404/1976)",
    siglaNorma: "LSA",
    dispositivo: "Art. 115, caput",
    ementa: "Voto abusivo e conflito de interesses do acionista",
    texto:
      "O acionista deve exercer o direito a voto no interesse da companhia; considerar-se-á abusivo o voto exercido com o fim de causar dano à companhia ou a outros acionistas, ou de obter, para si ou para outrem, vantagem a que não faz jus e de que resulte, ou possa resultar, prejuízo para a companhia ou para outros acionistas.",
    areas: ["direito empresarial", "direito societário"],
    sinonimos: ["voto abusivo", "conflito de interesses", "assembleia geral"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l6404consol.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "lsa-art116",
    tipo: "legislacao",
    norma: "Lei das Sociedades por Ações (Lei 6.404/1976)",
    siglaNorma: "LSA",
    dispositivo: "Art. 116",
    ementa: "Acionista controlador e seus deveres",
    texto:
      "Entende-se por acionista controlador a pessoa, natural ou jurídica, ou o grupo de pessoas vinculadas por acordo de voto, ou sob controle comum, que: a) é titular de direitos de sócio que lhe assegurem, de modo permanente, a maioria dos votos nas deliberações da assembléia-geral e o poder de eleger a maioria dos administradores da companhia; e b) usa efetivamente seu poder para dirigir as atividades sociais e orientar o funcionamento dos órgãos da companhia.",
    areas: ["direito empresarial", "direito societário"],
    sinonimos: ["controlador", "acordo de acionistas", "poder de controle"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l6404consol.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "lsa-art153",
    tipo: "legislacao",
    norma: "Lei das Sociedades por Ações (Lei 6.404/1976)",
    siglaNorma: "LSA",
    dispositivo: "Art. 153",
    ementa: "Dever de diligência do administrador",
    texto:
      "O administrador da companhia deve empregar, no exercício de suas funções, o cuidado e diligência que todo homem ativo e probo costuma empregar na administração dos seus próprios negócios.",
    areas: ["direito empresarial", "direito societário"],
    sinonimos: ["dever de diligência", "homem ativo e probo", "governança corporativa"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l6404consol.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "lsa-art155",
    tipo: "legislacao",
    norma: "Lei das Sociedades por Ações (Lei 6.404/1976)",
    siglaNorma: "LSA",
    dispositivo: "Art. 155, caput",
    ementa: "Dever de lealdade do administrador",
    texto:
      "O administrador deve servir com lealdade à companhia e manter reserva sobre os seus negócios, sendo-lhe vedado: I - usar, em benefício próprio ou de outrem, com ou sem prejuízo para a companhia, as oportunidades comerciais de que tenha conhecimento em razão do exercício de seu cargo; II - omitir-se no exercício ou proteção de direitos da companhia ou, visando à obtenção de vantagens, para si ou para outrem, deixar de aproveitar oportunidades de negócio de interesse da companhia; III - adquirir, para revender com lucro, bem ou direito que sabe necessário à companhia, ou que esta tencione adquirir.",
    areas: ["direito empresarial", "direito societário"],
    sinonimos: ["dever de lealdade", "desvio de oportunidade", "sigilo dos negócios"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l6404consol.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "lsa-art158",
    tipo: "legislacao",
    norma: "Lei das Sociedades por Ações (Lei 6.404/1976)",
    siglaNorma: "LSA",
    dispositivo: "Art. 158, caput",
    ementa: "Responsabilidade civil do administrador da companhia",
    texto:
      "O administrador não é pessoalmente responsável pelas obrigações que contrair em nome da sociedade e em virtude de ato regular de gestão; responde, porém, civilmente, pelos prejuízos que causar, quando proceder: I - dentro de suas atribuições ou poderes, com culpa ou dolo; II - com violação da lei ou do estatuto.",
    areas: ["direito empresarial", "direito societário", "direito civil"],
    sinonimos: ["ato regular de gestão", "responsabilidade do administrador", "violação do estatuto"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l6404consol.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },

  // ---------------------------------------------------------------------
  // Métodos consensuais e arbitragem
  // ---------------------------------------------------------------------
  {
    id: "arb-art1",
    tipo: "legislacao",
    norma: "Lei de Arbitragem (Lei 9.307/1996)",
    siglaNorma: "Lei 9.307/1996",
    dispositivo: "Art. 1º, caput",
    ementa: "Arbitrabilidade de direitos patrimoniais disponíveis",
    texto:
      "As pessoas capazes de contratar poderão valer-se da arbitragem para dirimir litígios relativos a direitos patrimoniais disponíveis.",
    areas: ["arbitragem", "direito processual civil", "direito civil"],
    sinonimos: ["arbitrabilidade", "direitos disponíveis", "juízo arbitral"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9307.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "arb-art2",
    tipo: "legislacao",
    norma: "Lei de Arbitragem (Lei 9.307/1996)",
    siglaNorma: "Lei 9.307/1996",
    dispositivo: "Art. 2º, caput e §§ 1º e 2º",
    ementa: "Arbitragem de direito ou de equidade",
    texto:
      "A arbitragem poderá ser de direito ou de eqüidade, a critério das partes. § 1º Poderão as partes escolher, livremente, as regras de direito que serão aplicadas na arbitragem, desde que não haja violação aos bons costumes e à ordem pública. § 2º Poderão, também, as partes convencionar que a arbitragem se realize com base nos princípios gerais de direito, nos usos e costumes e nas regras internacionais de comércio.",
    areas: ["arbitragem", "direito processual civil"],
    sinonimos: ["equidade", "lei aplicável", "usos e costumes"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9307.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "arb-art4",
    tipo: "legislacao",
    norma: "Lei de Arbitragem (Lei 9.307/1996)",
    siglaNorma: "Lei 9.307/1996",
    dispositivo: "Art. 4º",
    ementa: "Cláusula compromissória e contratos de adesão",
    texto:
      "A cláusula compromissória é a convenção através da qual as partes em um contrato comprometem-se a submeter à arbitragem os litígios que possam vir a surgir, relativamente a tal contrato. § 1º A cláusula compromissória deve ser estipulada por escrito, podendo estar inserta no próprio contrato ou em documento apartado que a ele se refira. § 2º Nos contratos de adesão, a cláusula compromissória só terá eficácia se o aderente tomar a iniciativa de instituir a arbitragem ou concordar, expressamente, com a sua instituição, desde que por escrito em documento anexo ou em negrito, com a assinatura ou visto especialmente para essa cláusula.",
    areas: ["arbitragem", "direito civil", "direito do consumidor"],
    sinonimos: ["cláusula compromissória", "contrato de adesão", "convenção de arbitragem"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9307.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "arb-art8",
    tipo: "legislacao",
    norma: "Lei de Arbitragem (Lei 9.307/1996)",
    siglaNorma: "Lei 9.307/1996",
    dispositivo: "Art. 8º",
    ementa: "Autonomia da cláusula e competência do árbitro",
    texto:
      "A cláusula compromissória é autônoma em relação ao contrato em que estiver inserta, de tal sorte que a nulidade deste não implica, necessariamente, a nulidade da cláusula compromissória. Parágrafo único. Caberá ao árbitro decidir de ofício, ou por provocação das partes, as questões acerca da existência, validade e eficácia da convenção de arbitragem e do contrato que contenha a cláusula compromissória.",
    areas: ["arbitragem", "direito processual civil"],
    sinonimos: ["kompetenz-kompetenz", "autonomia da cláusula", "competência-competência"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9307.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "arb-art18",
    tipo: "legislacao",
    norma: "Lei de Arbitragem (Lei 9.307/1996)",
    siglaNorma: "Lei 9.307/1996",
    dispositivo: "Art. 18",
    ementa: "Árbitro como juiz de fato e de direito",
    texto:
      "O árbitro é juiz de fato e de direito, e a sentença que proferir não fica sujeita a recurso ou a homologação pelo Poder Judiciário.",
    areas: ["arbitragem", "direito processual civil"],
    sinonimos: ["irrecorribilidade", "jurisdição arbitral", "sem homologação"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9307.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "arb-art31",
    tipo: "legislacao",
    norma: "Lei de Arbitragem (Lei 9.307/1996)",
    siglaNorma: "Lei 9.307/1996",
    dispositivo: "Art. 31",
    ementa: "Efeitos da sentença arbitral",
    texto:
      "A sentença arbitral produz, entre as partes e seus sucessores, os mesmos efeitos da sentença proferida pelos órgãos do Poder Judiciário e, sendo condenatória, constitui título executivo.",
    areas: ["arbitragem", "direito processual civil"],
    sinonimos: ["título executivo judicial", "coisa julgada arbitral", "eficácia da sentença arbitral"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9307.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "med-art1",
    tipo: "legislacao",
    norma: "Lei de Mediação (Lei 13.140/2015)",
    siglaNorma: "Lei 13.140/2015",
    dispositivo: "Art. 1º",
    ementa: "Definição legal de mediação",
    texto:
      "Esta Lei dispõe sobre a mediação como meio de solução de controvérsias entre particulares e sobre a autocomposição de conflitos no âmbito da administração pública. Parágrafo único. Considera-se mediação a atividade técnica exercida por terceiro imparcial sem poder decisório, que, escolhido ou aceito pelas partes, as auxilia e estimula a identificar ou desenvolver soluções consensuais para a controvérsia.",
    areas: ["mediação", "direito processual civil"],
    sinonimos: ["autocomposição", "terceiro imparcial", "solução consensual"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13140.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "med-art2",
    tipo: "legislacao",
    norma: "Lei de Mediação (Lei 13.140/2015)",
    siglaNorma: "Lei 13.140/2015",
    dispositivo: "Art. 2º",
    ementa: "Princípios que orientam a mediação",
    texto:
      "A mediação será orientada pelos seguintes princípios: I - imparcialidade do mediador; II - isonomia entre as partes; III - oralidade; IV - informalidade; V - autonomia da vontade das partes; VI - busca do consenso; VII - confidencialidade; VIII - boa-fé. § 1º Na hipótese de existir previsão contratual de cláusula de mediação, as partes deverão comparecer à primeira reunião de mediação. § 2º Ninguém será obrigado a permanecer em procedimento de mediação.",
    areas: ["mediação", "direito processual civil"],
    sinonimos: ["imparcialidade", "autonomia da vontade", "cláusula de mediação"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13140.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "med-art3",
    tipo: "legislacao",
    norma: "Lei de Mediação (Lei 13.140/2015)",
    siglaNorma: "Lei 13.140/2015",
    dispositivo: "Art. 3º",
    ementa: "Conflitos que podem ser objeto de mediação",
    texto:
      "Pode ser objeto de mediação o conflito que verse sobre direitos disponíveis ou sobre direitos indisponíveis que admitam transação. § 1º A mediação pode versar sobre todo o conflito ou parte dele. § 2º O consenso das partes envolvendo direitos indisponíveis, mas transigíveis, deve ser homologado em juízo, exigida a oitiva do Ministério Público.",
    areas: ["mediação", "direito processual civil"],
    sinonimos: ["direitos transigíveis", "homologação judicial", "oitiva do Ministério Público"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13140.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "med-art20",
    tipo: "legislacao",
    norma: "Lei de Mediação (Lei 13.140/2015)",
    siglaNorma: "Lei 13.140/2015",
    dispositivo: "Art. 20",
    ementa: "Termo final da mediação como título executivo",
    texto:
      "O procedimento de mediação será encerrado com a lavratura do seu termo final, quando for celebrado acordo ou quando não se justificarem novos esforços para a obtenção de consenso, seja por declaração do mediador nesse sentido ou por manifestação de qualquer das partes. Parágrafo único. O termo final de mediação, na hipótese de celebração de acordo, constitui título executivo extrajudicial e, quando homologado judicialmente, título executivo judicial.",
    areas: ["mediação", "direito processual civil"],
    sinonimos: ["termo final", "título executivo extrajudicial", "encerramento da mediação"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13140.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
  {
    id: "med-art30",
    tipo: "legislacao",
    norma: "Lei de Mediação (Lei 13.140/2015)",
    siglaNorma: "Lei 13.140/2015",
    dispositivo: "Art. 30, caput",
    ementa: "Confidencialidade do procedimento de mediação",
    texto:
      "Toda e qualquer informação relativa ao procedimento de mediação será confidencial em relação a terceiros, não podendo ser revelada sequer em processo arbitral ou judicial salvo se as partes expressamente decidirem de forma diversa ou quando sua divulgação for exigida por lei ou necessária para cumprimento de acordo obtido pela mediação.",
    areas: ["mediação", "direito processual civil"],
    sinonimos: ["sigilo da mediação", "informação confidencial", "prova emprestada"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13140.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO_AMPLIACAO,
  },
];
