import type { Fonte } from "./tipos";

const PLANALTO = "Presidência da República — texto compilado (planalto.gov.br)";
const CONFERIDO = "2026-09-02";

/**
 * Seed de legislação transcrita da fonte oficial.
 *
 * Este arquivo é deliberadamente pequeno e curado à mão. Ele NÃO é o corpus
 * final da plataforma — é o núcleo verificado que permite operar o V1 sem que
 * a IA precise inventar dispositivo nenhum. A ingestão automatizada do acervo
 * completo (LexML / Planalto) está descrita em docs/FUNDAMENTACAO.md e é o
 * primeiro item de infraestrutura do V2.
 *
 * Regra para incluir um dispositivo aqui: texto literal conferido contra a URL
 * oficial, com a data da conferência preenchida em `verificadoEm`.
 */
export const LEGISLACAO: Fonte[] = [
  // ---------------------------------------------------------------------
  // Constituição Federal de 1988
  // ---------------------------------------------------------------------
  {
    id: "cf88-art1",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 1º",
    ementa: "Fundamentos da República e titularidade do poder",
    texto:
      "A República Federativa do Brasil, formada pela união indissolúvel dos Estados e Municípios e do Distrito Federal, constitui-se em Estado Democrático de Direito e tem como fundamentos: I - a soberania; II - a cidadania; III - a dignidade da pessoa humana; IV - os valores sociais do trabalho e da livre iniciativa; V - o pluralismo político. Parágrafo único. Todo o poder emana do povo, que o exerce por meio de representantes eleitos ou diretamente, nos termos desta Constituição.",
    areas: ["direito constitucional", "teoria geral do estado", "ciência política"],
    sinonimos: ["soberania popular", "estado democrático de direito", "dignidade da pessoa humana"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art2",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 2º",
    ementa: "Separação dos Poderes",
    texto:
      "São Poderes da União, independentes e harmônicos entre si, o Legislativo, o Executivo e o Judiciário.",
    areas: ["direito constitucional", "teoria geral do estado", "ciência política"],
    sinonimos: ["tripartição de poderes", "freios e contrapesos", "montesquieu"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art3",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 3º",
    ementa: "Objetivos fundamentais da República",
    texto:
      "Constituem objetivos fundamentais da República Federativa do Brasil: I - construir uma sociedade livre, justa e solidária; II - garantir o desenvolvimento nacional; III - erradicar a pobreza e a marginalização e reduzir as desigualdades sociais e regionais; IV - promover o bem de todos, sem preconceitos de origem, raça, sexo, cor, idade e quaisquer outras formas de discriminação.",
    areas: ["direito constitucional", "direitos humanos"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-caput",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, caput",
    ementa: "Princípio da igualdade e direitos individuais",
    texto:
      "Todos são iguais perante a lei, sem distinção de qualquer natureza, garantindo-se aos brasileiros e aos estrangeiros residentes no País a inviolabilidade do direito à vida, à liberdade, à igualdade, à segurança e à propriedade, nos termos seguintes:",
    areas: ["direito constitucional", "direitos humanos"],
    sinonimos: ["isonomia", "direitos fundamentais"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-ii",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, II",
    ementa: "Princípio da legalidade",
    texto:
      "ninguém será obrigado a fazer ou deixar de fazer alguma coisa senão em virtude de lei;",
    areas: ["direito constitucional", "direito administrativo"],
    sinonimos: ["legalidade", "reserva legal"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-xxxv",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, XXXV",
    ementa: "Inafastabilidade da jurisdição",
    texto:
      "a lei não excluirá da apreciação do Poder Judiciário lesão ou ameaça a direito;",
    areas: ["direito constitucional", "direito processual civil"],
    sinonimos: ["acesso à justiça", "inafastabilidade do controle jurisdicional"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-liv",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, LIV",
    ementa: "Devido processo legal",
    texto:
      "ninguém será privado da liberdade ou de seus bens sem o devido processo legal;",
    areas: ["direito constitucional", "direito processual civil", "direito processual penal"],
    sinonimos: ["due process", "devido processo legal"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-lv",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, LV",
    ementa: "Contraditório e ampla defesa",
    texto:
      "aos litigantes, em processo judicial ou administrativo, e aos acusados em geral são assegurados o contraditório e ampla defesa, com os meios e recursos a ela inerentes;",
    areas: ["direito constitucional", "direito processual civil", "direito processual penal"],
    sinonimos: ["contraditório", "ampla defesa"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-lxiii",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, LXIII",
    ementa: "Direito ao silêncio do preso",
    texto:
      "o preso será informado de seus direitos, entre os quais o de permanecer calado, sendo-lhe assegurada a assistência da família e de advogado;",
    areas: ["direito constitucional", "direito processual penal", "direitos humanos"],
    sinonimos: ["direito ao silêncio", "nemo tenetur se detegere"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-lxviii",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, LXVIII",
    ementa: "Habeas corpus",
    texto:
      "conceder-se-á habeas corpus sempre que alguém sofrer ou se achar ameaçado de sofrer violência ou coação em sua liberdade de locomoção, por ilegalidade ou abuso de poder;",
    areas: ["direito constitucional", "direito processual penal", "direitos humanos"],
    sinonimos: ["habeas corpus", "remédio constitucional", "liberdade de locomoção"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art5-lxix",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 5º, LXIX",
    ementa: "Mandado de segurança",
    texto:
      "conceder-se-á mandado de segurança para proteger direito líquido e certo, não amparado por habeas corpus ou habeas data, quando o responsável pela ilegalidade ou abuso de poder for autoridade pública ou agente de pessoa jurídica no exercício de atribuições do Poder Público;",
    areas: ["direito constitucional", "direito administrativo"],
    sinonimos: ["mandado de segurança", "remédio constitucional", "direito líquido e certo"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art37-caput",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 37, caput",
    ementa: "Princípios da Administração Pública",
    texto:
      "A administração pública direta e indireta de qualquer dos Poderes da União, dos Estados, do Distrito Federal e dos Municípios obedecerá aos princípios de legalidade, impessoalidade, moralidade, publicidade e eficiência e, também, ao seguinte:",
    areas: ["direito administrativo", "direito constitucional"],
    sinonimos: ["LIMPE", "princípios da administração pública"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art44",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 44",
    ementa: "Poder Legislativo e bicameralismo",
    texto:
      "O Poder Legislativo é exercido pelo Congresso Nacional, que se compõe da Câmara dos Deputados e do Senado Federal. Parágrafo único. Cada legislatura terá a duração de quatro anos.",
    areas: ["direito constitucional", "ciência política", "teoria geral do estado"],
    sinonimos: ["congresso nacional", "bicameralismo", "poder legislativo"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art59",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 59",
    ementa: "Espécies normativas do processo legislativo",
    texto:
      "O processo legislativo compreende a elaboração de: I - emendas à Constituição; II - leis complementares; III - leis ordinárias; IV - leis delegadas; V - medidas provisórias; VI - decretos legislativos; VII - resoluções. Parágrafo único. Lei complementar disporá sobre a elaboração, redação, alteração e consolidação das leis.",
    areas: ["direito constitucional", "ciência política"],
    sinonimos: ["processo legislativo", "espécies normativas", "hierarquia das normas"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cf88-art102-caput",
    tipo: "legislacao",
    norma: "Constituição da República Federativa do Brasil de 1988",
    siglaNorma: "CF/88",
    dispositivo: "Art. 102, caput",
    ementa: "Competência do Supremo Tribunal Federal",
    texto:
      "Compete ao Supremo Tribunal Federal, precipuamente, a guarda da Constituição, cabendo-lhe:",
    areas: ["direito constitucional"],
    sinonimos: ["STF", "controle de constitucionalidade", "guarda da constituição"],
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },

  // ---------------------------------------------------------------------
  // LINDB
  // ---------------------------------------------------------------------
  {
    id: "lindb-art3",
    tipo: "legislacao",
    norma: "Lei de Introdução às Normas do Direito Brasileiro (Decreto-Lei 4.657/1942)",
    siglaNorma: "LINDB",
    dispositivo: "Art. 3º",
    ementa: "Obrigatoriedade da lei",
    texto: "Ninguém se escusa de cumprir a lei, alegando que não a conhece.",
    areas: ["introdução ao estudo do direito", "direito civil"],
    sinonimos: ["ignorantia legis", "obrigatoriedade das leis"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del4657compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "lindb-art2",
    tipo: "legislacao",
    norma: "Lei de Introdução às Normas do Direito Brasileiro (Decreto-Lei 4.657/1942)",
    siglaNorma: "LINDB",
    dispositivo: "Art. 2º",
    ementa: "Vigência e revogação da lei",
    texto:
      "Não se destinando à vigência temporária, a lei terá vigor até que outra a modifique ou revogue.",
    areas: ["introdução ao estudo do direito", "direito civil"],
    sinonimos: ["vigência", "revogação", "princípio da continuidade"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del4657compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },

  // ---------------------------------------------------------------------
  // Código Civil
  // ---------------------------------------------------------------------
  {
    id: "cc-art1",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 1º",
    ementa: "Capacidade de direito",
    texto: "Toda pessoa é capaz de direitos e deveres na ordem civil.",
    areas: ["direito civil"],
    sinonimos: ["personalidade jurídica", "capacidade de direito"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art2",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 2º",
    ementa: "Início da personalidade civil e direitos do nascituro",
    texto:
      "A personalidade civil da pessoa começa do nascimento com vida; mas a lei põe a salvo, desde a concepção, os direitos do nascituro.",
    areas: ["direito civil"],
    sinonimos: ["nascituro", "início da personalidade", "teoria natalista"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art104",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 104",
    ementa: "Requisitos de validade do negócio jurídico",
    texto:
      "A validade do negócio jurídico requer: I - agente capaz; II - objeto lícito, possível, determinado ou determinável; III - forma prescrita ou não defesa em lei.",
    areas: ["direito civil"],
    sinonimos: ["negócio jurídico", "plano da validade", "escada ponteana"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art186",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 186",
    ementa: "Ato ilícito e responsabilidade subjetiva",
    texto:
      "Aquele que, por ação ou omissão voluntária, negligência ou imprudência, violar direito e causar dano a outrem, ainda que exclusivamente moral, comete ato ilícito.",
    areas: ["direito civil"],
    sinonimos: ["ato ilícito", "responsabilidade civil subjetiva", "culpa", "dano moral"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art187",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 187",
    ementa: "Abuso de direito",
    texto:
      "Também comete ato ilícito o titular de um direito que, ao exercê-lo, excede manifestamente os limites impostos pelo seu fim econômico ou social, pela boa-fé ou pelos bons costumes.",
    areas: ["direito civil"],
    sinonimos: ["abuso de direito", "boa-fé objetiva"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art205",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 205",
    ementa: "Prazo geral de prescrição",
    texto:
      "A prescrição ocorre em dez anos, quando a lei não lhe haja fixado prazo menor.",
    areas: ["direito civil"],
    sinonimos: ["prescrição decenal", "prazo prescricional geral"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art389",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 389",
    ementa: "Inadimplemento e perdas e danos",
    texto:
      "Não cumprida a obrigação, responde o devedor por perdas e danos, mais juros e atualização monetária segundo índices oficiais regularmente estabelecidos, e honorários de advogado.",
    areas: ["direito civil"],
    sinonimos: ["inadimplemento", "perdas e danos", "mora"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art422",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 422",
    ementa: "Boa-fé objetiva nos contratos",
    texto:
      "Os contratantes são obrigados a guardar, assim na conclusão do contrato, como em sua execução, os princípios de probidade e boa-fé.",
    areas: ["direito civil"],
    sinonimos: ["boa-fé objetiva", "probidade contratual"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cc-art927",
    tipo: "legislacao",
    norma: "Código Civil (Lei 10.406/2002)",
    siglaNorma: "CC",
    dispositivo: "Art. 927",
    ementa: "Dever de reparar e responsabilidade objetiva pelo risco",
    texto:
      "Aquele que, por ato ilícito (arts. 186 e 187), causar dano a outrem, fica obrigado a repará-lo. Parágrafo único. Haverá obrigação de reparar o dano, independentemente de culpa, nos casos especificados em lei, ou quando a atividade normalmente desenvolvida pelo autor do dano implicar, por sua natureza, risco para os direitos de outrem.",
    areas: ["direito civil"],
    sinonimos: ["responsabilidade objetiva", "teoria do risco", "dever de indenizar"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },

  // ---------------------------------------------------------------------
  // Código de Processo Civil
  // ---------------------------------------------------------------------
  {
    id: "cpc-art1",
    tipo: "legislacao",
    norma: "Código de Processo Civil (Lei 13.105/2015)",
    siglaNorma: "CPC",
    dispositivo: "Art. 1º",
    ementa: "Interpretação conforme a Constituição",
    texto:
      "O processo civil será ordenado, disciplinado e interpretado conforme os valores e as normas fundamentais estabelecidos na Constituição da República Federativa do Brasil, observando-se as disposições deste Código.",
    areas: ["direito processual civil"],
    sinonimos: ["normas fundamentais do processo civil", "constitucionalização do processo"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cpc-art2",
    tipo: "legislacao",
    norma: "Código de Processo Civil (Lei 13.105/2015)",
    siglaNorma: "CPC",
    dispositivo: "Art. 2º",
    ementa: "Princípio dispositivo e impulso oficial",
    texto:
      "O processo começa por iniciativa da parte e se desenvolve por impulso oficial, salvo as exceções previstas em lei.",
    areas: ["direito processual civil"],
    sinonimos: ["princípio da inércia", "impulso oficial", "princípio dispositivo"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cpc-art10",
    tipo: "legislacao",
    norma: "Código de Processo Civil (Lei 13.105/2015)",
    siglaNorma: "CPC",
    dispositivo: "Art. 10",
    ementa: "Vedação à decisão surpresa",
    texto:
      "O juiz não pode decidir, em grau algum de jurisdição, com base em fundamento a respeito do qual não se tenha dado às partes oportunidade de se manifestar, ainda que se trate de matéria sobre a qual deva decidir de ofício.",
    areas: ["direito processual civil"],
    sinonimos: ["decisão surpresa", "contraditório substancial"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cpc-art300",
    tipo: "legislacao",
    norma: "Código de Processo Civil (Lei 13.105/2015)",
    siglaNorma: "CPC",
    dispositivo: "Art. 300",
    ementa: "Requisitos da tutela de urgência",
    texto:
      "A tutela de urgência será concedida quando houver elementos que evidenciem a probabilidade do direito e o perigo de dano ou o risco ao resultado útil do processo.",
    areas: ["direito processual civil"],
    sinonimos: ["tutela de urgência", "fumus boni iuris", "periculum in mora", "liminar"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cpc-art319",
    tipo: "legislacao",
    norma: "Código de Processo Civil (Lei 13.105/2015)",
    siglaNorma: "CPC",
    dispositivo: "Art. 319",
    ementa: "Requisitos da petição inicial",
    texto:
      "A petição inicial indicará: I - o juízo a que é dirigida; II - os nomes, os prenomes, o estado civil, a existência de união estável, a profissão, o número de inscrição no Cadastro de Pessoas Físicas ou no Cadastro Nacional da Pessoa Jurídica, o endereço eletrônico, o domicílio e a residência do autor e do réu; III - o fato e os fundamentos jurídicos do pedido; IV - o pedido com as suas especificações; V - o valor da causa; VI - as provas com que o autor pretende demonstrar a verdade dos fatos alegados; VII - a opção do autor pela realização ou não de audiência de conciliação ou de mediação.",
    areas: ["direito processual civil", "prática jurídica"],
    sinonimos: ["petição inicial", "requisitos da inicial", "peça processual"],
    url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },

  // ---------------------------------------------------------------------
  // Código Penal e Código de Processo Penal
  // ---------------------------------------------------------------------
  {
    id: "cp-art1",
    tipo: "legislacao",
    norma: "Código Penal (Decreto-Lei 2.848/1940)",
    siglaNorma: "CP",
    dispositivo: "Art. 1º",
    ementa: "Legalidade e anterioridade penal",
    texto:
      "Não há crime sem lei anterior que o defina. Não há pena sem prévia cominação legal.",
    areas: ["direito penal"],
    sinonimos: ["nullum crimen nulla poena sine lege", "anterioridade da lei penal", "legalidade penal"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cp-art121-caput",
    tipo: "legislacao",
    norma: "Código Penal (Decreto-Lei 2.848/1940)",
    siglaNorma: "CP",
    dispositivo: "Art. 121, caput",
    ementa: "Homicídio simples",
    texto: "Matar alguém: Pena - reclusão, de seis a vinte anos.",
    areas: ["direito penal"],
    sinonimos: ["homicídio", "crimes contra a vida"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cp-art155-caput",
    tipo: "legislacao",
    norma: "Código Penal (Decreto-Lei 2.848/1940)",
    siglaNorma: "CP",
    dispositivo: "Art. 155, caput",
    ementa: "Furto",
    texto:
      "Subtrair, para si ou para outrem, coisa alheia móvel: Pena - reclusão, de um a quatro anos, e multa.",
    areas: ["direito penal"],
    sinonimos: ["furto", "crimes contra o patrimônio"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cpp-art155",
    tipo: "legislacao",
    norma: "Código de Processo Penal (Decreto-Lei 3.689/1941)",
    siglaNorma: "CPP",
    dispositivo: "Art. 155",
    ementa: "Livre convencimento motivado e valor do inquérito",
    texto:
      "O juiz formará sua convicção pela livre apreciação da prova produzida em contraditório judicial, não podendo fundamentar sua decisão exclusivamente nos elementos informativos colhidos na investigação, ressalvadas as provas cautelares, não repetíveis e antecipadas.",
    areas: ["direito processual penal"],
    sinonimos: ["livre convencimento motivado", "valor probatório do inquérito"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },

  // ---------------------------------------------------------------------
  // Código de Defesa do Consumidor
  // ---------------------------------------------------------------------
  {
    id: "cdc-art2",
    tipo: "legislacao",
    norma: "Código de Defesa do Consumidor (Lei 8.078/1990)",
    siglaNorma: "CDC",
    dispositivo: "Art. 2º",
    ementa: "Conceito de consumidor",
    texto:
      "Consumidor é toda pessoa física ou jurídica que adquire ou utiliza produto ou serviço como destinatário final. Parágrafo único. Equipara-se a consumidor a coletividade de pessoas, ainda que indetermináveis, que haja intervindo nas relações de consumo.",
    areas: ["direito do consumidor", "direito civil"],
    sinonimos: ["consumidor", "destinatário final", "teoria finalista"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cdc-art3",
    tipo: "legislacao",
    norma: "Código de Defesa do Consumidor (Lei 8.078/1990)",
    siglaNorma: "CDC",
    dispositivo: "Art. 3º, caput",
    ementa: "Conceito de fornecedor",
    texto:
      "Fornecedor é toda pessoa física ou jurídica, pública ou privada, nacional ou estrangeira, bem como os entes despersonalizados, que desenvolvem atividade de produção, montagem, criação, construção, transformação, importação, exportação, distribuição ou comercialização de produtos ou prestação de serviços.",
    areas: ["direito do consumidor"],
    sinonimos: ["fornecedor", "relação de consumo"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cdc-art6-viii",
    tipo: "legislacao",
    norma: "Código de Defesa do Consumidor (Lei 8.078/1990)",
    siglaNorma: "CDC",
    dispositivo: "Art. 6º, VIII",
    ementa: "Inversão do ônus da prova",
    texto:
      "a facilitação da defesa de seus direitos, inclusive com a inversão do ônus da prova, a seu favor, no processo civil, quando, a critério do juiz, for verossímil a alegação ou quando for ele hipossuficiente, segundo as regras ordinárias de experiências;",
    areas: ["direito do consumidor", "direito processual civil"],
    sinonimos: ["inversão do ônus da prova", "hipossuficiência", "verossimilhança"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cdc-art14-caput",
    tipo: "legislacao",
    norma: "Código de Defesa do Consumidor (Lei 8.078/1990)",
    siglaNorma: "CDC",
    dispositivo: "Art. 14, caput",
    ementa: "Responsabilidade do fornecedor de serviços pelo fato do serviço",
    texto:
      "O fornecedor de serviços responde, independentemente da existência de culpa, pela reparação dos danos causados aos consumidores por defeitos relativos à prestação dos serviços, bem como por informações insuficientes ou inadequadas sobre sua fruição e riscos.",
    areas: ["direito do consumidor"],
    sinonimos: ["fato do serviço", "responsabilidade objetiva do fornecedor", "acidente de consumo"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
  {
    id: "cdc-art49",
    tipo: "legislacao",
    norma: "Código de Defesa do Consumidor (Lei 8.078/1990)",
    siglaNorma: "CDC",
    dispositivo: "Art. 49",
    ementa: "Direito de arrependimento",
    texto:
      "O consumidor pode desistir do contrato, no prazo de 7 dias a contar de sua assinatura ou do ato de recebimento do produto ou serviço, sempre que a contratação de fornecimento de produtos e serviços ocorrer fora do estabelecimento comercial, especialmente por telefone ou a domicílio.",
    areas: ["direito do consumidor"],
    sinonimos: ["direito de arrependimento", "prazo de reflexão", "compra online"],
    url: "https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },

  // ---------------------------------------------------------------------
  // CLT
  // ---------------------------------------------------------------------
  {
    id: "clt-art3",
    tipo: "legislacao",
    norma: "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
    siglaNorma: "CLT",
    dispositivo: "Art. 3º",
    ementa: "Conceito de empregado",
    texto:
      "Considera-se empregado toda pessoa física que prestar serviços de natureza não eventual a empregador, sob a dependência deste e mediante salário.",
    areas: ["direito do trabalho"],
    sinonimos: ["vínculo empregatício", "subordinação", "pessoalidade", "onerosidade"],
    url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm",
    origem: PLANALTO,
    verificadoEm: CONFERIDO,
  },
];
